# Generated by Django 3.0 on 2020-01-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='institution',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
