# Generated by Django 3.0 on 2020-01-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_auto_20200119_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='totalques',
            field=models.IntegerField(null=True),
        ),
    ]
