# Generated by Django 3.0 on 2020-01-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0008_selectedans_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='testname',
            field=models.CharField(default='bal', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresult',
            name='username',
            field=models.CharField(default='ball', max_length=255),
            preserve_default=False,
        ),
    ]
